version: '2'
services:
    lp-app:
        image: lp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://lp-postgresql:5432/lp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=lp-elasticsearch:9300
        ports:
            - 8080:8080
    lp-postgresql:
        extends:
            file: postgresql.yml
            service: lp-postgresql
    lp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: lp-elasticsearch
